In [1]:
import numpy as np 
import pandas as pd 
import nltk 
import os

In [2]:
test=pd.read_csv('fake-news/train.csv')

In [3]:
test.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
test.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [5]:
test.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [6]:
import nltk
import ssl

try:
    _create_unverified_https_context = ssl._create_unverified_context
except AttributeError:
    pass
else:
    ssl._create_default_https_context = _create_unverified_https_context

nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [7]:
nltk.download('stopwords')



[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/mrinalraj/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [8]:
test=test.dropna()

In [9]:
test.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [10]:
test['content'] = test['author']+' '+test['title']

In [11]:
y_test=test['label']

In [12]:
test=test.drop('label',axis=1)

In [13]:
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
import re
from sklearn.metrics import accuracy_score
from nltk.stem.porter import PorterStemmer

In [14]:
port=PorterStemmer()

In [15]:
def stemming(content):
    review = re.sub('[^a-zA-Z]',' ',str(content))
    review = review.lower()
    review = review.split()
    review = [port.stem(word) for word in review if not word in stopwords.words('english')]
    review = ' '.join(review)
    return review
test['content']=test['content'].apply(stemming)

In [16]:
x_test=test['content']

In [17]:
print(x_test.shape)
print(y_test.shape)


(18285,)
(18285,)


In [18]:
len(x_test)

18285

In [19]:
from keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer(num_words=5000,oov_token="<OOV>")


In [20]:
tokenizer.fit_on_texts(x_test)

In [21]:
tokenizerword_index = tokenizer.word_index
tokenizerword_index

{'<OOV>': 1,
 'new': 2,
 'time': 3,
 'york': 4,
 'trump': 5,
 'breitbart': 6,
 'hillari': 7,
 'clinton': 8,
 'donald': 9,
 'elect': 10,
 'u': 11,
 'say': 12,
 'michael': 13,
 'obama': 14,
 'news': 15,
 'john': 16,
 'com': 17,
 'presid': 18,
 'state': 19,
 'video': 20,
 'war': 21,
 'world': 22,
 'russia': 23,
 'vote': 24,
 'report': 25,
 'us': 26,
 'attack': 27,
 'comment': 28,
 'admin': 29,
 'year': 30,
 'american': 31,
 'day': 32,
 'call': 33,
 'hous': 34,
 'blogger': 35,
 'email': 36,
 'norepli': 37,
 'fbi': 38,
 'get': 39,
 'media': 40,
 'white': 41,
 'america': 42,
 'david': 43,
 'kill': 44,
 'polic': 45,
 'key': 46,
 'daniel': 47,
 'bill': 48,
 'campaign': 49,
 'charli': 50,
 'plan': 51,
 'democrat': 52,
 'e': 53,
 'pam': 54,
 'protest': 55,
 'support': 56,
 'first': 57,
 'one': 58,
 'make': 59,
 'brief': 60,
 'show': 61,
 'robert': 62,
 'mike': 63,
 'jame': 64,
 'black': 65,
 'even': 66,
 'win': 67,
 'b': 68,
 'anti': 69,
 'syria': 70,
 'j': 71,
 'right': 72,
 'back': 73,
 'take'

In [22]:
x_test=tokenizer.texts_to_sequences(x_test)

In [23]:
from tensorflow.keras.preprocessing.sequence import pad_sequences


In [24]:
mean=[]
for i in range(len(x_test)):
    mean.append(len(x_test[i]))

In [25]:
max(mean)

51

In [26]:
padded = pad_sequences(x_test, maxlen=50, padding="pre")
print(padded)

[[   0    0    0 ...  135 3855  582]
 [   0    0    0 ...  222 1436    6]
 [   0    0    0 ... 1159   39  118]
 ...
 [   0    0    0 ...    2    4    3]
 [   0    0    0 ...    1 3187    1]
 [   0    0    0 ...  305  117 1911]]


In [27]:
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout
from tensorflow.keras.models import Sequential

In [28]:
model = Sequential()
model.add(Embedding(5000,40,input_length=50))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(64,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
print(model.summary())


2022-02-13 10:52:22.229652: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 50, 40)            200000    
                                                                 
 dropout (Dropout)           (None, 50, 40)            0         
                                                                 
 lstm (LSTM)                 (None, 100)               56400     
                                                                 
 dropout_1 (Dropout)         (None, 100)               0         
                                                                 
 dense (Dense)               (None, 64)                6464      
                                                                 
 dropout_2 (Dropout)         (None, 64)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 6

In [29]:
x_test=np.array(padded)
y_test=np.array(y_test)

In [30]:
model.fit(x_test,y_test,epochs=20,batch_size=64)

Epoch 1/20
286/286 [==============================] - 9s 25ms/step - loss: 0.1633 - accuracy: 0.9343
Epoch 2/20
286/286 [==============================] - 7s 25ms/step - loss: 0.0184 - accuracy: 0.9949
Epoch 3/20
286/286 [==============================] - 7s 25ms/step - loss: 0.0059 - accuracy: 0.9984
Epoch 4/20
286/286 [==============================] - 7s 25ms/step - loss: 0.0039 - accuracy: 0.9989
Epoch 5/20
286/286 [==============================] - 7s 24ms/step - loss: 0.0038 - accuracy: 0.9990
Epoch 6/20
286/286 [==============================] - 7s 24ms/step - loss: 0.0017 - accuracy: 0.9995
Epoch 7/20
286/286 [==============================] - 7s 25ms/step - loss: 0.0014 - accuracy: 0.9997
Epoch 8/20
286/286 [==============================] - 7s 26ms/step - loss: 0.0045 - accuracy: 0.9990
Epoch 9/20
286/286 [==============================] - 8s 28ms/step - loss: 0.0015 - accuracy: 0.9995
Epoch 10/20
286/286 [==============================] - 8s 29ms/step - loss: 5.4134e-04 - ac

In [31]:
tokenizer_test=Tokenizer(num_words=5000,oov_token="<OOV>")

In [32]:
final=pd.read_csv('fake-news/test.csv')

In [33]:
final['title'][1]

'Russian warships ready to strike terrorists near Aleppo'

In [34]:
final['content'] = final['author']+' '+final['title']
final_content=final['content']
for i in range(len(final['content'])):
    if(final['content'][i]):
        final['content'][i] = final['title'][i]
        print(final['content'][i] )

/var/folders/4k/n2_9qsx90159nj77rssmh7fm0000gn/T/ipykernel_3501/4213519328.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['content'][i] = final['title'][i]


Specter of Trump Loosens Tongues, if Not Purse Strings, in Silicon Valley - The New York Times
Russian warships ready to strike terrorists near Aleppo
#NoDAPL: Native American Leaders Vow to Stay All Winter, File Lawsuit Against Police
Tim Tebow Will Attempt Another Comeback, This Time in Baseball - The New York Times
Keiser Report: Meme Wars (E995)
Trump is USA's antique hero. Clinton will be next president
Pelosi Calls for FBI Investigation to Find Out ’What the Russians Have on Donald Trump’ - Breitbart
Weekly Featured Profile – Randy Shannon
Urban Population Booms Will Make Climate Change Worse
nan
184 U.S. generals and admirals endorse Trump for Commander-In-Chief
“Working Class Hero” by John Brennon
The Rise of Mandatory Vaccinations Means the End of Medical Freedom
Communists Terrorize Small Business
Computer Programmer Comes Forward, Admits To Being Paid To Rig Voting Booths! TRUMP WAS RIGHT! • USA Newsflash
Thieves Take a Chunk of Change, All 221 Pounds of It, From a Berlin Mu

In [35]:
final

id                                              title  \
0     20800  Specter of Trump Loosens Tongues, if Not Purse...   
1     20801  Russian warships ready to strike terrorists ne...   
2     20802  #NoDAPL: Native American Leaders Vow to Stay A...   
3     20803  Tim Tebow Will Attempt Another Comeback, This ...   
4     20804                    Keiser Report: Meme Wars (E995)   
...     ...                                                ...   
5195  25995  The Bangladeshi Traffic Jam That Never Ends - ...   
5196  25996  John Kasich Signs One Abortion Bill in Ohio bu...   
5197  25997  California Today: What, Exactly, Is in Your Su...   
5198  25998  300 US Marines To Be Deployed To Russian Borde...   
5199  25999  Awkward Sex, Onscreen and Off - The New York T...   

                       author  \
0            David Streitfeld   
1                         NaN   
2               Common Dreams   
3               Daniel Victor   
4     Truth Broadcast Network   
...                       ...   
5195               Jody Rosen   
5196      Sheryl Gay Stolberg   
5197             Mike McPhate   
5198                      NaN   
5199              Teddy Wayne   

                                                   text  \
0     PALO ALTO, Calif.  —   After years of scorning...   
1     Russian warships ready to strike terrorists ne...   
2     Videos #NoDAPL: Native American Leaders Vow to...   
3     If at first you don’t succeed, try a different...   
4     42 mins ago 1 Views 0 Comments 0 Likes 'For th...   
...                                                 ...   
5195  Of all the dysfunctions that plague the world’...   
5196  WASHINGTON  —   Gov. John Kasich of Ohio on Tu...   
5197  Good morning. (Want to get California Today by...   
5198  « Previous - Next » 300 US Marines To Be Deplo...   
5199  Perhaps you’ve seen the new TV series whose pi...   

                                                content  
0     Specter of Trump Loosens Tongues, if Not Purse...  
1     Russian warships ready to strike terrorists ne...  
2     #NoDAPL: Native American Leaders Vow to Stay A...  
3     Tim Tebow Will Attempt Another Comeback, This ...  
4                       Keiser Report: Meme Wars (E995)  
...                                                 ...  
5195  The Bangladeshi Traffic Jam That Never Ends - ...  
5196  John Kasich Signs One Abortion Bill in Ohio bu...  
5197  California Today: What, Exactly, Is in Your Su...  
5198  300 US Marines To Be Deployed To Russian Borde...  
5199  Awkward Sex, Onscreen and Off - The New York T...  

[5200 rows x 5 columns]

In [36]:
id = final['id']

In [37]:
final['content']=final['content'].apply(stemming)

In [38]:
x_test=final['content']
x_test

0       specter trump loosen tongu purs string silicon...
1       russian warship readi strike terrorist near al...
2       nodapl nativ american leader vow stay winter f...
3       tim tebow attempt anoth comeback time basebal ...
4                                keiser report meme war e
                              ...                        
5195      bangladeshi traffic jam never end new york time
5196    john kasich sign one abort bill ohio veto rest...
5197         california today exactli sushi new york time
5198                us marin deploy russian border norway
5199                   awkward sex onscreen new york time
Name: content, Length: 5200, dtype: object

In [39]:
tokenizer.fit_on_texts(x_test)

In [40]:
x_test

0       specter trump loosen tongu purs string silicon...
1       russian warship readi strike terrorist near al...
2       nodapl nativ american leader vow stay winter f...
3       tim tebow attempt anoth comeback time basebal ...
4                                keiser report meme war e
                              ...                        
5195      bangladeshi traffic jam never end new york time
5196    john kasich sign one abort bill ohio veto rest...
5197         california today exactli sushi new york time
5198                us marin deploy russian border norway
5199                   awkward sex onscreen new york time
Name: content, Length: 5200, dtype: object

In [42]:
x_test=tokenizer.texts_to_sequences(x_test)

In [43]:
padded_test = pad_sequences(x_test, maxlen=50, padding="pre")

In [44]:
padded_test

array([[   0,    0,    0, ...,    2,    4,    3],
       [   0,    0,    0, ...,  288,  538,  279],
       [   0,    0,    0, ...,  881, 1072,   40],
       ...,
       [   0,    0,    0, ...,    2,    4,    3],
       [   0,    0,    0, ...,   60,  110, 3285],
       [   0,    0,    0, ...,    2,    4,    3]], dtype=int32)

In [45]:
pre=model.predict(padded_test)

In [47]:


pre=np.round(pre)



In [50]:
pre
pre=pre.astype(int)
pre

array([[0],
       [1],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [51]:


final_sub = pd.DataFrame()
final_sub['id']=id
final_sub['label'] = pre
final_sub.to_csv('final_sub.csv',index=False)



In [55]:

import joblib
 
joblib.dump(model, 'fake_news.pkl')

INFO:tensorflow:Assets written to: ram://c46a1472-1f4c-46d6-8edb-146c32614211/assets


INFO:tensorflow:Assets written to: ram://c46a1472-1f4c-46d6-8edb-146c32614211/assets


['fake_news.pkl']